const departmentsAndProcedures = {
  "Anesthesiology": [
    "General anaesthesia",
    "Regional anaesthesia",
    "Local anaesthesia",
    "Sedation",
  ],
  "Emergency Medicine": [
    "First Aid",
    "Cardiopulmonary resuscitation",
    "Intravenous therapy",
    "Electrocardiogram",
  ],
  "Family Medicine": [
    "Allergy injections",
    "Biopsy and excision of skin lesions",
    "Flu shots and immunizations",
    "Incision and drainage of abscesses",
    "Intrauterine device (IUD) placement and removal",
    "Joint injections",
    "Lab services",
    "Minor surgery",
    "Newborn and well-child care",
    "Placement and removal of contraceptive implants",
    "Obstetrics",
    "Palliative care",
    "Physical exams for sports",
    "Treadmill testing",
    "Women's health services",
  ],
  "Geriatrics": [
    "Emergency Geriatric Care services",
    "Geriatric Acute Inpatient services",
    "Geriatric Ambulatory services",
    "Geriatric Cognitive Impairment services",
    "Geriatric Consultation Liaison services",
    "Geriatric Evaluation and Management services",
    "Geriatric Interim Care services",
    "Geriatric Rehabilitation services",
    "Ortho-geriatric services",
  ],
  "Neurology": [
    "Lumbar Puncture",
    "Electromyography",
    "Tensilon Test",
    "Electroencephalogram",
    "Sleep Study",
  ],
  "Neurosurgery": [
    "Anterior Cervical Discectomy",
    "Craniotomy",
    "Chiari Decompression",
    "Laminectomy",
    "Epilepsy Surgery",
    "Spinal Fusion",
    "Microdiscectomy",
    "Ventriculostomy",
    "Ventriculoperitoneal Shunt",
  ],
  "Obstetrics and Gynecology": [
    "Adhesiolysis",
    "Cervical (Cone) Biopsy",
    "Colporrhaphy",
    "Colposcopy",
    "Dilation and Curettage",
    "Endometrial Ablation",
    "Endometrial or Uterine Biopsy",
    "Fluid-Contrast Ultrasound",
    "Hysterectomy",
    "Hysterosalpingography",
    "Hysteroscopy",
    "Myomectomy",
    "Oophorectomy",
    "Pelvic Ultrasound",
    "Pelviscopy",
    "Selective Salpingography",
    "Toluidine Blue Dye Test",
    "Trachelectomy",
    "Tubal Ligation",
    "Uterine (artery) Fibroid Embolization",
    "Vulvectomy",
  ],
  "Ophthalmology & Visual Sciences": [
    "Cataract Surgery",
    "Vitrectomy",
    "LASIK",
    "DMEK",
    "DSAEK",
    "Corneal Transplant",
    "Laser Surgery",
    "Trabeculectomy",
  ],
  "Orthopedic Surgery": [
    "Knee Surgery",
    "Shoulder and Elbow Surgery",
    "Hand and Wrist Surgery",
    "Hip Surgery",
    "Foot and Ankle Surgery",
  ],
  "Otolaryngology and Communication Sciences": [
    "Blepharoplasty",
    "Endoscopic sinus surgery",
    "Excision and biopsy",
    "Facial plastic surgery",
    "Myringotomy and pressure equalization (PE) tube placement",
    "Neck dissection",
    "Septoplasty",
    "Surgery for snoring or obstructive sleep apnea (OSA)",
    "Thyroid Surgery",
    "Tonsillectomy or adenoidectomy",
    "Tracheostomy",
    "Tympanoplasty",
  ],
  "Pathology": [
    "Full blood count",
    "Liver function tests",
    "Iron studies",
    "Thyroid stimulating hormone (TSH) quantification",
    "Urinalysis",
    "Typical pathology test procedures",
    "Blood test",
    "Urine sample",
    "Stool sample",
  ],
  "Pediatrics": [
    "Appendectomy",
    "Biliary atresia",
    "Congenital defects",
    "Gallbladder surgery",
    "Gastroschisis",
    "Bowed chest",
    "Reproductive defects",
    "Removal of the spleen",
    "Bariatric surgery",
    "Removal of diseased intestines",
    "Hernia surgery",
    "GERD treatment",
    "Abnormal pathways",
    "Imperforate anus",
  ],
  "Physical Medicine and Rehabilitation": [
    "Acupuncture",
    "Amputation rehabilitation",
    "Arthritis rehabilitation",
    "Brain rehabilitation",
    "Cancer rehabilitation",
    "Hand therapy",
    "Hip replacement",
    "Inpatient rehabilitation",
    "Knee replacement",
    "Lung volume reduction surgery",
    "Manual therapy",
    "Multiple sclerosis therapy",
    "Neck pain therapy",
    "Orthopedic manual therapy",
    "Orthopedic physical therapy",
    "Osteoporosis rehabilitation",
    "Pediatric rehabilitation",
    "Pulmonary rehabilitation",
    "Running evaluation",
    "Spasticity therapy",
    "Sports rehabilitation",
    "Stroke rehabilitation",
    "Swallowing therapy",
    "Vestibular rehabilitation",
    "Work rehabilitation",
    "Wrist fracture treatment",
  ],
  "Psychiatry and Behavioral Sciences": [
    "Psychiatric diagnostic evaluation",
    "Psychotherapy",
    "Family psychotherapy",
    "Group psychotherapy",
    "Electroconvulsive therapy",
    "Neuropsychological testing",
    "Psychological testing evaluation services",
  ],
  "Radiology": [
    "Computed tomography scans",
    "Fluoroscopy",
    "Magnetic resonance imaging",
    "Mammography",
    "Nuclear medicine",
    "X-rays",
    "Positron emission tomography",
    "Ultrasound",
  ],
  "Urology": [
    "Vasectomy",
    "Vasectomy Reversal",
    "Cystoscopy",
    "Prostate Procedures",
    "Ureteroscopy",
    "Lithotripsy",
    "Orchiopexy",
    "Penile Plication",
    "Penile Implants & Prosthesis",
    "Male circumcision",
  ],
}

/* departmentsAndProcedures = {
 *    department1: [ ... procedure1 ],
 *    department2: [ ... procedure2 ],
 * }
 */


// gets all departments
const departments = Object.keys(departmentsAndProcedures)

// gets all procedures
let procedures = []
departments.map((department) => {
  procedures = [...procedures, ...departmentsAndProcedures[department]]
})

module.exports = {
  departmentsAndProcedures,
  departments,
  procedures,
}