const m15 = 900000 // 15 mins
const m30 = 1800000
const h1 = 3600000 // 1 hour
const h1m30 = 5400000
const h2 = 7200000 
const h3 = 10800000

module.exports = {
  "General anaesthesia":m15,
  "Regional anaesthesia":m15,
  "Local anaesthesia":m15,
  "Sedation":m15,
  "First Aid":m15,
  "Cardiopulmonary resuscitation":m15,
  "Intravenous therapy":m30,
  "Electrocardiogram":m30,
  "Allergy injections":m15,
  "Biopsy and excision of skin lesions":m30,
  "Flu shots and immunizations":m15,
  "Incision and drainage of abscesses":m30,
  "Intrauterine device (IUD) placement and removal":h1m30,
  "Joint injections":m30,
  "Lab services":m30,
  "Minor surgery":m30,
  "Newborn and well-child care":h3,
  "Placement and removal of contraceptive implants":h2,
  "Obstetrics":h1,
  "Palliative care":h1,
  "Physical exams for sports":h1,
  "Treadmill testing":m30,
  "Women's health services":m30,
  "Emergency Geriatric Care services":h1,
  "Geriatric Acute Inpatient services":h1m30,
  "Geriatric Ambulatory services":h1,
  "Geriatric Cognitive Impairment services":h1m30,
  "Geriatric Consultation Liaison services":h1,
  "Geriatric Evaluation and Management services":h1m30,
  "Geriatric Interim Care services":h1,
  "Geriatric Rehabilitation services":h1,
  "Ortho-geriatric services":h1,
  "Lumbar Puncture":h1m30,
  "Electromyography":m30,
  "Tensilon Test":h3,
  "Electroencephalogram":m15,
  "Sleep Study":h3,
  "Anterior Cervical Discectomy":h3,
  "Craniotomy":h3,
  "Chiari Decompression":h3,
  "Laminectomy":h3,
  "Epilepsy Surgery":h3,
  "Spinal Fusion":h3,
  "Microdiscectomy":h3,
  "Ventriculostomy":h3,
  "Ventriculoperitoneal Shunt":h3,
  "Adhesiolysis":h3,
  "Cervical (Cone) Biopsy":h2,
  "Colporrhaphy":h1m30,
  "Colposcopy":h1m30,
  "Dilation and Curettage":h2,
  "Endometrial Ablation":h1m30,
  "Endometrial or Uterine Biopsy":h1m30,
  "Fluid-Contrast Ultrasound":h1,
  "Hysterectomy":h1m30,
  "Hysterosalpingography":m30,
  "Hysteroscopy":m30,
  "Myomectomy":m30,
  "Oophorectomy":m30,
  "Pelvic Ultrasound":m30,
  "Pelviscopy":h2,
  "Selective Salpingography":h1m30,
  "Toluidine Blue Dye Test":h1,
  "Trachelectomy":h1m30,
  "Tubal Ligation":h1,
  "Uterine (artery) Fibroid Embolization":h1,
  "Vulvectomy":h1,
  "Cataract Surgery":m30,
  "Vitrectomy":h1m30,
  "LASIK":m30,
  "DMEK":m30,
  "DSAEK":m30,
  "Corneal Transplant":h2,
  "Laser Surgery":m15,
  "Trabeculectomy":h1,
  "Knee Surgery":h1m30,
  "Shoulder and Elbow Surgery":h1m30,
  "Hand and Wrist Surgery":h1m30,
  "Hip Surgery":h2,
  "Foot and Ankle Surgery":h2,
  "Blepharoplasty":h1m30,
  "Endoscopic sinus surgery":h3,
  "Excision and biopsy":h3,
  "Facial plastic surgery":h3,
  "Myringotomy and pressure equalization (PE) tube placement":h3,
  "Neck dissection":h3,
  "Septoplasty":h1,
  "Surgery for snoring or obstructive sleep apnea (OSA)":h3,
  "Thyroid Surgery":h3,
  "Tonsillectomy or adenoidectomy":h1,
  "Tracheostomy":m30,
  "Tympanoplasty":m15,
  "Full blood count":m15,
  "Liver function tests":m15,
  "Iron studies":m15,
  "Thyroid stimulating hormone (TSH) quantification":m30,
  "Urinalysis":m15,
  "Typical pathology test procedures":m15,
  "Blood test":h1,
  "Urine sample":m30,
  "Stool sample":m30,
  "Appendectomy":m30,
  "Biliary atresia":h3,
  "Congenital defects":h1,
  "Gallbladder surgery":h3,
  "Gastroschisis":h1,
  "Bowed chest":h1,
  "Reproductive defects":h1,
  "Removal of the spleen":h1,
  "Bariatric surgery":h3,
  "Removal of diseased intestines":h2,
  "Hernia surgery":h1,
  "GERD treatment":h1,
  "Abnormal pathways":m30,
  "Imperforate anus":m30,
  "Acupuncture":m30,
  "Amputation rehabilitation":m30,
  "Arthritis rehabilitation":m30,
  "Brain rehabilitation":h1,
  "Cancer rehabilitation":h1m30,
  "Hand therapy":m15,
  "Hip replacement":h3,
  "Inpatient rehabilitation":h1m30,
  "Knee replacement":h1m30,
  "Lung volume reduction surgery":h3,
  "Manual therapy":h1,
  "Multiple sclerosis therapy":h1m30,
  "Neck pain therapy":h1,
  "Orthopedic manual therapy":m30,
  "Orthopedic physical therapy":m30,
  "Osteoporosis rehabilitation":m30,
  "Pediatric rehabilitation":m30,
  "Pulmonary rehabilitation":m30,
  "Running evaluation":m30,
  "Spasticity therapy":m30,
  "Sports rehabilitation":m15,
  "Stroke rehabilitation":m30,
  "Swallowing therapy":m15,
  "Vestibular rehabilitation":m15,
  "Work rehabilitation":m15,
  "Wrist fracture treatment":m15,
  "Psychiatric diagnostic evaluation":m30,
  "Psychotherapy":m30,
  "Family psychotherapy":m30,
  "Group psychotherapy":m30,
  "Electroconvulsive therapy":m15,
  "Neuropsychological testing":m30,
  "Psychological testing evaluation services":m30,
  "Computed tomography scans":m30,
  "Fluoroscopy":m30,
  "Magnetic resonance imaging":m15,
  "Mammography":m15,
  "Nuclear medicine":m15,
  "X-rays":m15,
  "Positron emission tomography":m15,
  "Ultrasound":m15,
  "Vasectomy":m30,
  "Vasectomy Reversal":m30,
  "Cystoscopy":m30,
  "Prostate Procedures":m15,
  "Ureteroscopy":m30,
  "Lithotripsy":h1,
  "Orchiopexy":m30,
  "Penile Plication":h1,
  "Penile Implants & Prosthesis":h1,
  "Male circumcision":m30,
}